# Generated by Django 5.0.7 on 2024-07-18 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_profile_photo_profile_facebook_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebBasicInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='網頁標題')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='網頁Logo')),
            ],
            options={
                'verbose_name': '網頁標題 & logo',
                'verbose_name_plural': '網頁標題 & logo',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '個人資料', 'verbose_name_plural': '個人資料'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='聯絡地址'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_link',
            field=models.URLField(blank=True, verbose_name='Facebook 連結'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_link',
            field=models.URLField(blank=True, verbose_name='Instagram 連結'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='聯絡電話'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='real_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='真實姓名'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用戶'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube_link',
            field=models.URLField(blank=True, verbose_name='YouTube 連結'),
        ),
    ]
