# Generated by Django 5.0.7 on 2024-07-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_aboutus_options_aboutus_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='simple_introduce',
            field=models.CharField(blank=True, help_text='至多100個字', max_length=100, null=True, verbose_name='簡單介紹'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(blank=True, help_text='至多10個字', max_length=10, null=True, verbose_name='標題'),
        ),
    ]
