# Generated by Django 5.0.7 on 2024-07-18 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_aboutus_simple_introduce_alter_aboutus_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='電子郵件')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話號碼')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('product_name', models.CharField(max_length=100, verbose_name='產品名稱')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='價格')),
                ('description', models.TextField(verbose_name='描述')),
                ('cover_image', models.ImageField(upload_to='products/', verbose_name='商品封面圖片')),
            ],
        ),
        migrations.CreateModel(
            name='SellerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100, verbose_name='賣家姓名')),
                ('seller_image', models.ImageField(upload_to='sellers/', verbose_name='圖片')),
                ('target_url', models.URLField(verbose_name='目標網址')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='商品照片')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.productinfo', verbose_name='產品')),
            ],
        ),
        migrations.AddField(
            model_name='productinfo',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.sellerinfo', verbose_name='賣家'),
        ),
    ]
