# Generated by Django 5.0.7 on 2024-07-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_productinfo_sellerinfo_productimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': '4.關於我們', 'verbose_name_plural': '4.關於我們'},
        ),
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'verbose_name': '3.輪播圖', 'verbose_name_plural': '3.輪播圖'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '1.個人資料', 'verbose_name_plural': '1.個人資料'},
        ),
        migrations.AlterModelOptions(
            name='sellerinfo',
            options={'verbose_name': '5.新增賣家', 'verbose_name_plural': '5.新增賣家'},
        ),
        migrations.AlterModelOptions(
            name='webbasicinf',
            options={'verbose_name': '2.網頁標題 & logo', 'verbose_name_plural': '2.網頁標題 & logo'},
        ),
    ]
