# Generated by Django 5.0.7 on 2024-07-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapIframe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_iframe', models.TextField(help_text='請輸入地圖的iframe，範例格式:\n        <iframe class="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3653.2541148558166!2d120.42691457479046!3d23.702617790610038!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x346eba072ee22f11%3A0x558aed05907207d7!2z5ZyL56uL6JmO5bC-56eR5oqA5aSn5a24!5e0!3m2!1szh-TW!2stw!4v1720886263664!5m2!1szh-TW!2stw"\n        width="600" height="450" style="border:0;" allowfullscreen="" \n        loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>', verbose_name='地圖嵌入代碼')),
            ],
        ),
    ]
