# Generated by Django 5.0.7 on 2024-07-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_mapiframe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapiframe',
            options={'verbose_name': '6.嵌入地圖', 'verbose_name_plural': '6.嵌入地圖'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default=100, help_text='至多10個字', max_length=10, verbose_name='標題'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='price',
            field=models.IntegerField(verbose_name='價格'),
        ),
    ]
