# Generated by Django 5.0.7 on 2024-07-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_carouselimage_author_carouselimage_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='author',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='header',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='標頭'),
        ),
    ]
