# Generated by Django 5.0.7 on 2024-07-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_carouselimage_author_carouselimage_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='topic',
        ),
    ]
