# Generated by Django 5.0.7 on 2024-08-04 07:18

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_carouselimage_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='顏色選擇'),
        ),
        migrations.AlterField(
            model_name='mapiframe',
            name='map_iframe',
            field=models.TextField(help_text='\n        請輸入地圖的iframe，範例格式:\n        <pre>\n        &lt;iframe class="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3653.2541148558166!2d120.42691457479046!3d23.702617790610038!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x346eba072ee22f11%3A0x558aed05907207d7!2z5ZyL56uL6JmO5bC-56eR5oqA5aSn5a24!5e0!3m2!1szh-TW!2stw!4v1720886263664!5m2!1szh-TW!2stw" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"&gt;&lt;/iframe&gt;\n        </pre>', verbose_name='地圖嵌入代碼'),
        ),
    ]
