# Generated by Django 5.0.7 on 2024-08-04 07:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_carouselimage_color_alter_mapiframe_map_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='文字顏色選擇'),
        ),
    ]
