# Generated by Django 5.0.4 on 2025-02-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_order_created_at_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='merchant_trade_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='訂單編號'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='尚未付款', max_length=20, verbose_name='狀態'),
        ),
    ]
