# Generated by Django 5.0.4 on 2025-02-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_order_merchant_trade_no_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': '訂單商品', 'verbose_name_plural': '訂單商品'},
        ),
    ]
