# Generated by Django 5.0.4 on 2025-02-04 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_orderitem_price_alter_orderitem_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECPayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=20, verbose_name='商家編號')),
                ('hash_key', models.CharField(max_length=50, verbose_name='Hash Key')),
                ('hash_iv', models.CharField(max_length=50, verbose_name='Hash IV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecpay_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '商家綠界金流資訊',
                'verbose_name_plural': '商家綠界金流資訊',
            },
        ),
    ]
