# Generated by Django 5.0.4 on 2025-02-04 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_ecpayinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecpayinfo',
            options={'verbose_name': '7.商家綠界金流資訊', 'verbose_name_plural': '7.商家綠界金流資訊'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '8.訂單', 'verbose_name_plural': '8.訂單'},
        ),
    ]
